services:
  resume-parser:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    restart: always
